core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('employee.urls'))
]

employee/urls.py
from django.urls import path
from employee.views import index

urlpatterns = [
    path('', index, name='index'),
]

employee/models.py
from django.db import models


class Department(models.Model):
    DEPARTMENT_LEVEL = (
        ("1", "Первый уровень"),
        ("2", "Второй уровень"),
        ("3", "Третий уровень"),
        ("4", "Четвертый уровень"),
        ("5", "Пятый уровень"),
    )
    
    name = models.CharField(max_length=155)
    level = models.CharField(max_length=1, choices=DEPARTMENT_LEVEL, blank=False)

    def __str__(self):
        return self.name


class Employee(models.Model):
    fullname = models.CharField(max_length=255)
    job_title = models.CharField(max_length=155)
    employment_date = models.DateField(auto_now_add=True)
    salary = models.DecimalField(max_digits=8, decimal_places=2)
    department = models.ForeignKey(Department, on_delete=models.PROTECT,)

    def __str__(self):
        return self.fullname

employee/views.py
from django.shortcuts import render
from employee.models import Department, Employee

def index(request):
    context = {}
    context['employee'] = Employee.objects.all()
    context['departments'] = Department.objects.all()
    context['departments_first'] = Department.objects.filter(level='1')
    context['departments_second'] = Department.objects.filter(level='2')
    context['departments_third'] = Department.objects.filter(level='3')
    context['departments_fourth'] = Department.objects.filter(level='4')
    context['departments_fifth'] = Department.objects.filter(level='5')

    return render(request, 'index.html', context=context)

templates/index.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Traffic Light | Древовидная диаграмма сотрудников</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'bootstrap/css/bootstrap.min.css' %}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'font-awesome/css/font-awesome.min.css' %}"
    />

    <script
      type="text/javascript"
      src="{% static 'js/jquery-1.10.2.min.js' %}"
    ></script>
    <script
      type="text/javascript"
      src="{% static 'bootstrap/js/bootstrap.min.js' %}"
    ></script>
  </head>
  <body>
    <div class="container">
      <div class="page-header">
        <h1>Traffic Light <small>Древовидная диаграмма сотрудников </small></h1>
      </div>

      <!-- Tree View - START -->
      <div class="container">
        <div class="row">
          {% if departments %}
          <div class="col-md-4 col-md-offset-4">
            <ul id="treeview">
              {% if departments_first %}
              <li data-icon-cls="fa fa-bars">
                Первый уровень
                <ul id="treeview">
                  {% for department in departments_first %}
                  <li data-icon-cls="fa fa-building">
                    {{department.name|title}}
                    <ul>
                      {% for employee in department.employee_set.all %}
                      <li data-icon-cls="fa fa-address-book-o">
			      {{employee.fullname}} - {{employee.job_title}}
                      </li>
                      {% endfor %}
                    </ul>
                  </li>
                  {% endfor %}
                </ul>
              </li>
              {% endif %} {% if departments_second %}
              <li data-icon-cls="fa fa-bars">
                Второй уровень
                <ul id="treeview">
                  {% for department in departments_second %}
                  <li data-icon-cls="fa fa-building">
                    {{department.name|title}}
                    <ul>
                      {% for employee in department.employee_set.all %}
                      <li data-icon-cls="fa fa-address-book-o">
                        {{employee.fullname}} - {{employee.job_title}}
                      </li>
                      {% endfor %}
                    </ul>
                  </li>
                  {% endfor %}
                </ul>
              </li>
              {% endif %} {% if departments_third %}
              <li data-icon-cls="fa fa-bars">
                Третий уровень
                <ul id="treeview">
                  {% for department in departments_third %}
                  <li data-icon-cls="fa fa-bars">
                    {{department.name|title}}
                    <ul>
                      {% for employee in department.employee_set.all %}
                      <li data-icon-cls="fa fa-address-book-o">
                        {{employee.fullname}} - {{employee.job_title}}
                      </li>
                      {% endfor %}
                    </ul>
                  </li>
                  {% endfor %}
                </ul>
              </li>
              {% endif %} {% if departments_fourth %}
              <li data-icon-cls="fa fa-bars">
                Четвертый уровень
                <ul id="treeview">
                  {% for department in departments_fourth %}
                  <li data-icon-cls="fa fa-building">
                    {{department.name|title}}
                    <ul>
                      {% for employee in department.employee_set.all %}
                      <li data-icon-cls="fa fa-address-book-o">
                        {{employee.fullname}} - {{employee.job_title}}
                      </li>
                      {% endfor %}
                    </ul>
                  </li>
                  {% endfor %}
                </ul>
              </li>
              {% endif %} {% if departments_fifth %}
              <li data-icon-cls="fa fa-bars">
                Пятый уровень
                <ul id="treeview">
                  {% for department in departments_fifth %}
                  <li data-icon-cls="fa fa-building">
                    {{department.name|title}}
                    <ul>
                      {% for employee in department.employee_set.all %}
                      <li data-icon-cls="fa fa-address-book-o">
                        {{employee.fullname}} - {{employee.job_title}}
                      </li>
                      {% endfor %}
                    </ul>
                  </li>
                  {% endfor %}
                </ul>
              </li>
              {% endif %}
            </ul>
          </div>
          {% else %}
          <h3>Пожалуйста, добавьте информацию о сотруднике в <a href="{% url 'admin:index' %}">админ панель</a></h3> 
          {% endif %}
        </div>
      </div>

      <!-- you need to include the ShieldUI CSS and JS assets in order for the TreeView widget to work -->
      <link
        rel="stylesheet"
        type="text/css"
        href="{% static 'shieldui.css' %}"
      />
      <script type="text/javascript" src="{% static 'shieldui.js' %}"></script>

      <script type="text/javascript">
        jQuery(function ($) {
          $("#treeview").shieldTreeView();
        });
      </script>
      <!-- Tree View - END -->
    </div>
  </body>
</html>